### ISSUE TITLE
Notice when trying to activate the plugin when WooCommerce is not active

### ISSUE THREAD

**Issue by gedex** [woothemes/woocommerce-gateway-stripe#28]
```
Notice: Use of undefined constant WC_VERSION - assumed 'WC_VERSION' in /srv/www/wc.demo/htdocs/wp-content/plugins/woocommerce-gateway-stripe/woocommerce-gateway-stripe.php on line 193

Notice: Use of undefined constant WC_VERSION - assumed 'WC_VERSION' in /srv/www/wc.demo/htdocs/wp-content/plugins/woocommerce-gateway-stripe/woocommerce-gateway-stripe.php on line 199
The plugin could not be activated. The minimum WooCommerce version required for this plugin is 2.5.0. You are running WC_VERSION.
```

Make sure to check whether `WC_VERSION` is defined or not.

**Comment by fjarrett** [comment]
+1 for this @gedex!

I think it would be better to put a notice in the admin and let the plugin remain activated, just not functional, until WooCommerce is activated. Perhaps even showing an admin notice.

IMO making the requirement that plugins must be activated in a particular order is not a very good UX. It just puts more burden on the user to perform a task in some particular way that to them just seems arbitrary.

Additionally, this would break any script trying to activate plugins unless they do it in the correct order:

Breaks `wp plugin activate woocommerce-gateway-stripe woocommerce`
Works `wp plugin activate woocommerce woocommerce-gateway-stripe`

Since there is no programatic way to detect plugin dependency in core, I think it's probably better not to try to enforce it.

**Comment by gedex** [comment]
@fjarrett Thanks for your suggestion. I was thinking the same line as you -- it shouldn't auto-deactivate if dependency is not satisfied. I've logged [here](https://github.com/woothemes/woocommerce-gateway-stripe/issues/47).
