### ISSUE TITLE
Disallow Prepaid Debit Cards

### ISSUE THREAD

**Issue by geeklore** [woothemes/woocommerce-gateway-stripe#63]
#### What I expected

The option for store owners to disallow the use of Prepaid Debit Cards.

#### What happened instead

There is no way to disallow. Please see this [reference](https://support.stripe.com/questions/how-can-i-see-which-type-of-card-my-customer-is-using) per Dwain.

Ticket: #[458946](https://woothemes.zendesk.com/agent/tickets/458946)
-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
I am not sure if there is a way to do this without actually processing the payment.

**Comment by quasel** [comment]
there is because when you do just do the check -> tokens you get in the Response the Type of the Card ... could be possible before that as the the Credit Card Icon changes based on the Number of the Card ...

**Comment by roykho** [comment]
@quasel - can you please point me to the documentation to this?

**Comment by quasel** [comment]
https://support.stripe.com/questions/how-can-i-see-which-type-of-card-my-customer-is-using
https://stripe.com/docs/api#token_object

it's in the response from the request to https://api.stripe.com/v1/tokens

antoher intresting point is 
https://www.masteringmodernpayments.com/blog/how-to-check-cvc-and-address-with-stripe-js

because if you use a multi step checkout it's nice to be able to check cvc/zip before the charge atempt at the end of the process ....

**Comment by roykho** [comment]
Right, I've seen those documentations already. Now the question is for first time subscriber that needs a token, how do you go about obtaining a token without processing it first? I am looking for a way to do this without having to create the card if it isn't going to be used.

**Comment by quasel** [comment]
well i guess the only way is to fetch a token - because this does't lead to an authorization and dont store it :P - that's what happens in the multi step echekcout is use - token's created in my case it does even a cvc/zip check by adding an amount to create token - and all togehter is just on the last page ...
